name: Selenium Test

on:
  push:
    branches:
      - main

jobs:
  selenium-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Install Google Chrome
        run: |
          sudo apt-get update
          sudo apt-get install -y wget curl gnupg
          curl -sSL https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb -o google-chrome.deb
          sudo apt install -y ./google-chrome.deb

      - name: Install dependencies for headless Chrome
        run: |
          sudo apt-get update
          sudo apt-get install -y \
          libxss1 \
          libappindicator3-1 \
          libgdk-pixbuf2.0-0 \
          libnss3 \
          libgdk-pixbuf2.0-0 \
          libasound2t64 \
          fonts-liberation \
          libatk-bridge2.0-0 \
          libatk1.0-0 \
          libgbm1 \
          libnspr4 \
          libnss3 \
          libx11-xcb1 \
          xdg-utils \
          libu2f-udev

      - name: Set up ChromeDriver (for Selenium)
        run: |
          # Create the directory for ChromeDriver
          mkdir -p $HOME/.local/bin
          
          # Fetch the latest ChromeDriver version
          LATEST=$(wget -qO- https://chromedriver.storage.googleapis.com/LATEST_RELEASE)
          if [ -z "$LATEST" ]; then
            echo "Failed to fetch the latest chromedriver version."
            exit 1
          fi
          echo "Latest ChromeDriver version: $LATEST"
          
          # Download and install the latest version of ChromeDriver
          wget https://chromedriver.storage.googleapis.com/${LATEST}/chromedriver_linux64.zip
          
          # Extract the chromedriver and move it to the correct location
          unzip chromedriver_linux64.zip -d $HOME/.local/bin
          
          # Make the chromedriver executable
          chmod +x $HOME/.local/bin/chromedriver
          
          # Add chromedriver to the PATH
          export PATH=$HOME/.local/bin:$PATH
          echo "$HOME/.local/bin" >> $GITHUB_PATH
      

      - name: Build and run tests
        run: mvn clean test -X

      - name: Upload test report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: testng-report
          path: target/surefire-reports/testng-results.html