name: Selenium Test

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Set up ChromeDriver (for Selenium)
        run: |
          # Install dependencies for running headless Chrome
          sudo apt-get update
          sudo apt-get install -y wget unzip

          # Create the directory for ChromeDriver
          mkdir -p $HOME/.local/bin

          # Download and install the latest version of ChromeDriver
          LATEST=$(wget -qO- https://chromedriver.storage.googleapis.com/LATEST_RELEASE)
          wget https://chromedriver.storage.googleapis.com/${LATEST}/chromedriver_linux64.zip

          # Extract the chromedriver and move it to the correct location
          unzip chromedriver_linux64.zip -d $HOME/.local/bin

          # Make the chromedriver executable
          chmod +x $HOME/.local/bin/chromedriver

          # Add chromedriver to the PATH
          echo "$HOME/.local/bin" >> $GITHUB_PATH
      

      - name: Build and run tests
        run: mvn clean test -X  # Enable debug logging for Maven

      - name: Upload test report
        uses: actions/upload-artifact@v4
        with:
          name: testng-report
          path: target/surefire-reports/testng-results.xml